
<!-- 3 Column Banners Starts -->
<div class="col3-banners">
    <div class="container">
        <ul class="row list-unstyled">
            <li class="col-sm-4">
                <img src="<?php echo $sys['config']['theme_url']; ?>/images/banners/3col-banner1.png" alt="banners" class="img-responsive" />
            </li>
            <li class="col-sm-4">
                <img src="<?php echo $sys['config']['theme_url']; ?>/images/banners/3col-banner2.png" alt="banners" class="img-responsive" />
            </li>
            <li class="col-sm-4">
                <img src="<?php echo $sys['config']['theme_url'] ?>/images/banners/3col-banner3.png" alt="banners" class="img-responsive" />
            </li>
        </ul>
    </div>
</div>
<!-- 3 Column Banners Ends -->