<!-- 2 Column Banners Starts -->
<div class="col2-banners">
    <div class="container">
        <ul class="row list-unstyled">
            <li class="col-sm-4">
                <img src="<?php echo $sys['config']['theme_url']; ?>/images/banners/2col-banner1.png" alt="banners" class="img-responsive" />
            </li>
            <li class="col-sm-8">
                <img src="<?php echo $sys['config']['theme_url']; ?>/images/banners/2col-banner2.png" alt="banners" class="img-responsive" />
            </li>
        </ul>
    </div>
</div>
<!-- 2 Column Banners Ends -->
