<!-- Footer Section Starts -->
<footer id="footer-area">
    <!-- Footer Links Starts -->
    <div class="footer-links">
        <!-- Container Starts -->
        <div class="container">
            <!-- Information Links Starts -->
            <div class="col-md-3 col-sm-6">
                <h5>Information</h5>
                <ul>
                    <li><a href="<?php echo $sys['config']['site_url']; ?>/about">About Us</a></li>                    
                </ul>
            </div>
            <!-- Information Links Ends -->            
            <!-- Customer Service Links Starts -->
            <div class="col-md-3 col-sm-6">
                <h5>Service</h5>
                <ul>
                    <li><a href="#">Compare Product</a></li>
                    <li><a href="#">Compare Price</a></li>
                    <li><a href="#">Site Map</a></li>                                        
                </ul>
            </div>
            <!-- Customer Service Links Ends -->
            <!-- Follow Us Links Starts -->
            <div class="col-md-3 col-sm-6">
                <h5>Follow Us</h5>
                <ul>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">RSS</a></li>
                    <li><a href="#">YouTube</a></li>
                </ul>
            </div>
            <!-- Follow Us Links Ends -->
            <!-- Contact Us Starts -->
            <div class="col-md-3 col-sm-12 last">
                <h5>Contact Us</h5>
                <ul>
                    <li>eValueBazaar</li>                    
                    <li>Email: <a href="#">info@evaluebazaar.com</a></li>								
                </ul>
                <h4 class="lead">
                    <!--Tel: <span></span>-->
                </h4>
            </div>
            <!-- Contact Us Ends -->
        </div>
        <!-- Container Ends -->
    </div>
    <!-- Footer Links Ends -->
    <!-- Copyright Area Starts -->
    <div class="copyright">
        <!-- Container Starts -->
        <div class="container">
            <!-- Starts -->
            <p class="pull-left">
                &nbsp; 2014 eValueBazaar
            </p>
            <!-- Ends -->
            <!-- Payment Gateway Links Starts -->
            <!--<ul class="pull-right list-inline">
                <li><img src="<?php echo $sys['config']['theme_url']; ?>/images/payment-icon/cirrus.png" alt="PaymentGateway" /></li>
                <li><img src="<?php echo $sys['config']['theme_url']; ?>/images/payment-icon/paypal.png" alt="PaymentGateway" /></li>
                <li><img src="<?php echo $sys['config']['theme_url']; ?>/images/payment-icon/visa.png" alt="PaymentGateway" /></li>
                <li><img src="<?php echo $sys['config']['theme_url']; ?>/images/payment-icon/mastercard.png" alt="PaymentGateway" /></li>
                <li><img src="<?php echo $sys['config']['theme_url']; ?>/images/payment-icon/americanexpress.png" alt="PaymentGateway" /></li>
            </ul>-->
            <!-- Payment Gateway Links Ends -->
        </div>
        <!-- Container Ends -->
    </div>
    <!-- Copyright Area Ends -->
</footer>
<!-- Footer Section Ends -->