<div id="main-container" class="container">                    
    <!-- Breadcrumb Starts -->
    <ol class="breadcrumb">
        <li><a href="index.html">Home</a></li>
        <li class="active">404 Page</li>
    </ol>
    <!-- Breadcrumb Ends -->
    <!-- Main Heading Starts -->
    <h2 class="main-heading text-center">
        404 Page
    </h2>
    <!-- Main Heading Ends -->
    <!-- Content Starts -->
    <div class="content-box text-center">
        <h4 class="special-heading">oops !</h4>
        <h5>
            The page you were looking for could not be found.
        </h5>
        <br />
        <p>
            <a href="<?php echo $sys['config']['site_url']; ?>" class="btn btn-warning text-uppercase">Back to Home</a>
        </p>
    </div>
    <!-- Content Ends -->   
</div>