<?php
$cartitems = Sys_getCartItems();
$carttotal = Sys_getCartTotal();
?>
<!--banner-->
<div class="banner1">
    <div class="container">
        <h3><a href="<?php echo $sys['config']['site_url']; ?>">Home</a> / <span>Cart</span></h3>
    </div>
</div>
<!--banner-->
<div class="content">
    <div class="cart-items">
        <div class="container">
            <h2>My Shopping Bag (<?php echo count($cartitems); ?>)</h2> 
            <?php foreach($cartitems as $cartitem) { ?>
            <div class="cart-header">
                <div class="close1" onclick="window.location.href='<?php echo $sys['config']['site_url'] ?>/requests.php?f=deletefromcart&cart_id=<?php echo $cartitem['id']; ?>'"> </div>
                <div class="cart-sec simpleCart_shelfItem">
                    <div class="cart-item cyc">
                        <img src="images/p15.jpg" class="img-responsive" alt="">
                    </div>
                    <div class="cart-item-info">
                        <h3><a href="#"> <?php echo $cartitem['product_name']; ?> </a><span>Pickup time:</span></h3>
                        <ul class="qty">
                            <li><p>Price: <?php echo $cartitem['price'] . " x " . $cartitem['qty']; ?></p></li>
                            <li><p>FREE delivery</p></li>
                        </ul>
                        <div class="delivery">
                            <p>Total : <?php echo $cartitem['total']; ?></p>
                            <span>Delivered in 1-1:30 hours</span>
                            <div class="clearfix"></div>
                        </div>	
                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>     
            <?php } ?>
            <div class="pull-right">
                <a href="<?php echo $sys['config']['site_url']; ?>/checkout" class="btn btn-primary">Checkout</a>
            </div>
        </div>
    </div>
    <!-- checkout -->	
</div>