<script>
    $(document).ready(function () {
        $("#owl-demo").owlCarousel({
            items: 1,
            lazyLoad: true,
            autoPlay: true,
            navigation: false,
            navigationText: false,
            pagination: true,
        });
    });
</script>
<?php
$product = Sys_getProductBySlug(trim($_GET['slug']));
$reviews = Sys_getReviews($product['id']);
$relatedproducts = Sys_getProductsByCategoryId($product['category']['id'], 0, 4);
?>
<!--banner-->
<div class="banner1">
    <div class="container">
        <h3><a href="<?php echo $sys['config']['site_url']; ?>">Home</a> / <span>Single</span></h3>
    </div>
</div>
<!--banner-->
<div class="content">
    <!--single-->
    <div class="single-wl3">
        <div class="container">
            <div class="single-grids">
                <div class="col-md-9 single-grid">
                    <div clas="single-top">
                        <div class="single-left">
                            <div class="flexslider">
                                <div class="flex-viewport" style="overflow: hidden; position: relative;">
                                    <ul class="slides">
                                        <?php $images = $product['imagesR']; ?>
                                        <?php foreach ($images as $img) { ?>
                                            <li data-thumb="<?php echo $img; ?>">
                                                <div class="thumb-image"> <img src="<?php echo $img; ?>" data-imagezoom="true" class="img-responsive"> </div>
                                            </li>
                                        <?php } ?>                                     
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="single-right simpleCart_shelfItem">
                            <h4><?php echo $product['name']; ?></h4>
                            <div class="block">
                                <div class="starbox small ghosting"> </div>
                            </div>
                            <p class="price item_price"><i class="fa fa-inr"></i> <?php echo $product['sellers'][$sys['config']['defaultSeller']]['price']; ?></p>
                            <div class="description">
                                <p><span>Quick Overview : </span> <?php echo nl2br($product['short_description']); ?></p>
                            </div>
                            <div class="color-quality">
                                <h6>Quantity :</h6>
                                <div class="quantity"> 
                                    <div class="quantity-select">                           
                                        <div class="entry value-minus1">&nbsp;</div>
                                        <div class="entry value1"><span>1</span></div>
                                        <div class="entry value-plus1 active">&nbsp;</div>
                                    </div>
                                </div>                                
                            </div>
                            <div class="women">
                                <form id="addtocartform" name="addtocartform" action="<?php echo $sys['config']['site_url'].'/requests.php?f=addtocart'; ?>">
                                    <input type="hidden" name="product_id" value="<?php echo $product['id']; ?>"/>
                                    <input type="hidden" name="seller_id" value="<?php echo $sys['config']['defaultSeller']; ?>"/>
                                    <input type="hidden" name="product_sku" value="<?php echo $product['sku']; ?>"/>
                                    <input type="hidden" name="product_name" value="<?php echo $product['name']; ?>"/>
                                    <input type="hidden" name="product_color" value="NA"/>
                                    <input type="hidden" name="product_size" value="NA"/>
                                    <input id="product_qty" type="hidden" name="product_qty" value="1"/>
                                    <input type="hidden" name="note" value="NA"/>                                                                   
                                    <input type="submit" name="addtocart" class="my-cart-b item_add" value="Add To Cart"/>
                                </form>
                            </div>
                            <div class="social-icon">
                                <a href="#"><i class="icon"></i></a>
                                <a href="#"><i class="icon1"></i></a>
                                <a href="#"><i class="icon2"></i></a>
                                <a href="#"><i class="icon3"></i></a>
                            </div>
                        </div>
                        <div class="clearfix"> </div>
                    </div>
                </div>
                <div class="col-md-3 single-grid1">
                    <h3>Related Products</h3>
                    <?php foreach ($relatedproducts as $relatedproduct) { 
                        $pimg = "http://placehold.it/62x95";
                        foreach ($relatedproduct['imagesR'] as $img) {
                            $pimg = $pimg;
                        }
                        ?>
                    <div class="recent-grids">
                        <div class="recent-left">
                            <a href="<?php echo $sys['config']['site_url']."/product/". $relatedproduct['slug']; ?>"><img class="img-responsive " src="<?php echo $pimg; ?>" alt=""></a>	
                        </div>
                        <div class="recent-right">
                            <h6 class="best2"><a href="<?php echo $sys['config']['site_url']."/product/". $relatedproduct['slug']; ?>"><?php echo $relatedproduct['name'] ?> </a></h6>
                            <div class="block">
                                <div class="starbox small ghosting"> </div>
                            </div>
                            <span class=" price-in1"> INR <?php echo $relatedproduct['sellers'][$sys['config']['defaultSeller']]['price']; ?></span>
                        </div>	
                        <div class="clearfix"> </div>
                    </div>
                    <?php } ?>
                </div>
                <div class="clearfix"> </div>
            </div>
            <!--Product Description-->
            <div class="product-w3agile">
                <h3 class="tittle1">Product Description</h3>
                <div class="product-grids">
                    <div class="col-md-4 product-grid">
                        <div id="owl-demo" class="owl-carousel">
                            <div class="item">
                                <div class="recent-grids">
                                    <div class="recent-left">
                                        <a href="single.html"><img class="img-responsive " src="images/r.jpg" alt=""></a>	
                                    </div>
                                    <div class="recent-right">
                                        <h6 class="best2"><a href="single.html">Lorem ipsum dolor </a></h6>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>
                                        <span class=" price-in1"> $ 29.00</span>
                                    </div>	
                                    <div class="clearfix"> </div>
                                </div>
                                <div class="recent-grids">
                                    <div class="recent-left">
                                        <a href="single.html"><img class="img-responsive " src="images/r1.jpg" alt=""></a>	
                                    </div>
                                    <div class="recent-right">
                                        <h6 class="best2"><a href="single.html">Duis aute irure </a></h6>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>
                                        <span class=" price-in1"> $ 19.00</span>
                                    </div>	
                                    <div class="clearfix"> </div>
                                </div>
                                <div class="recent-grids">
                                    <div class="recent-left">
                                        <a href="single.html"><img class="img-responsive " src="images/r2.jpg" alt=""></a>	
                                    </div>
                                    <div class="recent-right">
                                        <h6 class="best2"><a href="single.html">Lorem ipsum dolor </a></h6>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>
                                        <span class=" price-in1"> $ 19.00</span>
                                    </div>
                                    <div class="clearfix"> </div>
                                </div>
                                <div class="recent-grids">
                                    <div class="recent-left">
                                        <a href="single.html"><img class="img-responsive " src="images/r3.jpg" alt=""></a>	
                                    </div>
                                    <div class="recent-right">
                                        <h6 class="best2"><a href="single.html">Ut enim ad minim </a></h6>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>
                                        <span class=" price-in1">$ 45.00</span>
                                    </div>	
                                    <div class="clearfix"> </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="recent-grids">
                                    <div class="recent-left">
                                        <a href="single.html"><img class="img-responsive " src="images/r4.jpg" alt=""></a>	
                                    </div>
                                    <div class="recent-right">
                                        <h6 class="best2"><a href="single.html">Lorem ipsum dolor </a></h6>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>
                                        <span class=" price-in1"> $ 29.00</span>
                                    </div>	
                                    <div class="clearfix"> </div>
                                </div>
                                <div class="recent-grids">
                                    <div class="recent-left">
                                        <a href="single.html"><img class="img-responsive " src="images/r5.jpg" alt=""></a>	
                                    </div>
                                    <div class="recent-right">
                                        <h6 class="best2"><a href="single.html">Duis aute irure </a></h6>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>
                                        <span class=" price-in1"> $ 19.00</span>
                                    </div>	
                                    <div class="clearfix"> </div>
                                </div>
                                <div class="recent-grids">
                                    <div class="recent-left">
                                        <a href="single.html"><img class="img-responsive " src="images/r2.jpg" alt=""></a>	
                                    </div>
                                    <div class="recent-right">
                                        <h6 class="best2"><a href="single.html">Lorem ipsum dolor </a></h6>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>
                                        <span class=" price-in1"> $ 19.00</span>
                                    </div>
                                    <div class="clearfix"> </div>
                                </div>
                                <div class="recent-grids">
                                    <div class="recent-left">
                                        <a href="single.html"><img class="img-responsive " src="images/r3.jpg" alt=""></a>	
                                    </div>
                                    <div class="recent-right">
                                        <h6 class="best2"><a href="single.html">Ut enim ad minim </a></h6>
                                        <div class="block">
                                            <div class="starbox small ghosting"> </div>
                                        </div>
                                        <span class=" price-in1">$ 45.00</span>
                                    </div>	
                                    <div class="clearfix"> </div>
                                </div>
                            </div>
                        </div>
                        <img class="img-responsive " src="images/woo2.jpg" alt="">
                    </div>
                    <div class="col-md-8 product-grid1">
                        <div class="tab-wl3">
                            <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
                                <ul id="myTab" class="nav nav-tabs left-tab" role="tablist">
                                    <li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Description</a></li>
                                    <li role="presentation"><a href="#reviews" role="tab" id="reviews-tab" data-toggle="tab" aria-controls="reviews">Reviews (1)</a></li>

                                </ul>
                                <div id="myTabContent" class="tab-content">
                                    <div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
                                        <div class="descr">
                                            <h4>Suspendisse laoreet, augue vel mattis </h4>
                                            <p><?php echo nl2br($product['long_description']); ?></p>
                                            <p class="quote">Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
                                            <div class="video">
                                                <iframe src="https://player.vimeo.com/video/22158502" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                                            </div>
                                            <ul>
                                                <li> Twin button front fastening</li>
                                                <li> Length:65cm</li>
                                                <li> Regular fit</li>
                                                <li> Notched lapels</li>
                                                <li> Internal pockets</li>
                                                <li> Centre-back vent </li>
                                                <li> Material : Outer: 40% Linen &amp; 40% Polyamide; Body Lining: 100% Cotton; Lining: 100% Acetate</li>
                                            </ul>
                                            <p class="quote">Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>

                                        </div>
                                    </div>
                                    <div role="tabpanel" class="tab-pane fade" id="reviews" aria-labelledby="reviews-tab">
                                        <div class="descr">
                                            <div class="reviews-top">
                                                <div class="reviews-left">
                                                    <img src="images/men3.jpg" alt=" " class="img-responsive">
                                                </div>
                                                <div class="reviews-right">
                                                    <ul>
                                                        <li><a href="#">Admin</a></li>
                                                        <li><a href="#"><i class="glyphicon glyphicon-share" aria-hidden="true"></i>Reply</a></li>
                                                    </ul>
                                                    <p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit.</p>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                            <div class="reviews-bottom">
                                                <h4>Add Reviews</h4>
                                                <p>Your email address will not be published. Required fields are marked *</p>
                                                <p>Your Rating</p>
                                                <div class="block">
                                                    <div class="starbox small ghosting"><div class="positioner"><div class="stars"><div class="ghost" style="width: 42.5px; display: none;"></div><div class="colorbar" style="width: 42.5px;"></div><div class="star_holder"><div class="star star-0"></div><div class="star star-1"></div><div class="star star-2"></div><div class="star star-3"></div><div class="star star-4"></div></div></div></div></div>
                                                </div>
                                                <form action="#" method="post">
                                                    <label>Your Review </label>
                                                    <textarea type="text" Name="Message" onfocus="this.value = '';" onblur="if (this.value == '') {
                                                                        this.value = 'Message...';
                                                                    }" required="">Message...</textarea>
                                                    <div class="row">
                                                        <div class="col-md-6 row-grid">
                                                            <label>Name</label>
                                                            <input type="text" value="Name" Name="Name" onfocus="this.value = '';" onblur="if (this.value == '') {
                                                                                this.value = 'Name';
                                                                            }" required="">
                                                        </div>
                                                        <div class="col-md-6 row-grid">
                                                            <label>Email</label>
                                                            <input type="email" value="Email" Name="Email" onfocus="this.value = '';" onblur="if (this.value == '') {
                                                                                this.value = 'Email';
                                                                            }" required="">
                                                        </div>
                                                        <div class="clearfix"></div>
                                                    </div>
                                                    <input type="submit" value="SEND">
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <div role="tabpanel" class="tab-pane fade" id="custom" aria-labelledby="custom-tab">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"> </div>
                </div>
            </div>
            <!--Product Description-->
        </div>
    </div>
    <!--single-->
</div>