    <!--Latest Fashion Products-->

<div class="latest-w3">
        <div class="container">
            <!--<h3 class="tittle1">Latest Fashion Trends</h3>-->
            <div class="latest-grids">
                <div class="col-md-4 latest-grid">
                    <div class="latest-top">
                        <img  src="<?php echo $sys['config']['theme_url']; ?>/images/l1.jpg" class="img-responsive"  alt="">
                        <div class="latest-text">
                            <h4>Men</h4>
                        </div>
                     <!--   <div class="latest-text2 hvr-sweep-to-top">
                            <h4>-50%</h4>
                        </div>-->
                    </div>
                </div>
                <div class="col-md-4 latest-grid">
                    <div class="latest-top">
                        <img  src="<?php echo $sys['config']['theme_url']; ?>/images/l2.jpg" class="img-responsive"  alt="">
                        <div class="latest-text">
                            <h4>Shoes</h4>
                        </div>
                        <!--<div class="latest-text2 hvr-sweep-to-top">
                            <h4>-20%</h4>
                        </div>-->
                    </div>
                </div>
                <div class="col-md-4 latest-grid">
                    <div class="latest-top">
                        <img  src="<?php echo $sys['config']['theme_url']; ?>/images/l3.jpg" class="img-responsive"  alt="">
                        <div class="latest-text">
                            <h4>Women</h4>
                        </div>
                        <!--<div class="latest-text2 hvr-sweep-to-top">
                            <h4>-50%</h4>
                        </div>-->
                    </div>
                </div>
                <div class="col-md-4 latest-grid">
                    <div class="latest-top">
                        <img  src="<?php echo $sys['config']['theme_url']; ?>/images/l1.jpg" class="img-responsive"  alt="">
                        <div class="latest-text">
                            <h4>Men</h4>
                        </div>
                     <!--   <div class="latest-text2 hvr-sweep-to-top">
                            <h4>-50%</h4>
                        </div>-->
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="latest-grids">
                <div class="col-md-4 latest-grid">
                    <div class="latest-top">
                        <img  src="<?php echo $sys['config']['theme_url']; ?>/images/l4.jpg" class="img-responsive"  alt="">
                        <div class="latest-text">
                            <h4>Watch</h4>
                        </div>
                       <!--  <div class="latest-text2 hvr-sweep-to-top">
                           <h4>-45%</h4>
                        </div>-->
                    </div>
                </div>
                <div class="col-md-4 latest-grid">
                    <div class="latest-top">
                        <img  src="<?php echo $sys['config']['theme_url']; ?>/images/l5.jpg" class="img-responsive"  alt="">
                        <div class="latest-text">
                            <h4>Bag</h4>
                        </div>
                        <!-- <div class="latest-text2 hvr-sweep-to-top">
                           <h4>-10%</h4>
                        </div>-->
                    </div>
                </div>
                <div class="col-md-4 latest-grid">
                    <div class="latest-top">
                        <img  src="<?php echo $sys['config']['theme_url']; ?>/images/l6.jpg" class="img-responsive"  alt="">
                        <div class="latest-text">
                            <h4>Cameras</h4>
                        </div>
                        <!--<div class="latest-text2 hvr-sweep-to-top">
                            <h4>-30%</h4>
                        </div>-->
                    </div>
                </div>
                <div class="col-md-4 latest-grid">
                    <div class="latest-top">
                        <img  src="<?php echo $sys['config']['theme_url']; ?>/images/l4.jpg" class="img-responsive"  alt="">
                        <div class="latest-text">
                            <h4>Watch</h4>
                        </div>
                       <!--  <div class="latest-text2 hvr-sweep-to-top">
                           <h4>-45%</h4>
                        </div>-->
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>